quarkus.application.name=inventory-api

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true

quarkus.datasource.devservices.enabled=true

cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
